Repository OHBA-analysis/osl-dynamics, pull requests merged in 2023-01, with the labels that each got.

#54 Enhance mode analysis: SMA and plotting matrices
  doc/development.rst
  osl_dynamics/analysis/modes.py
  osl_dynamics/utils/plotting.py
Labels: bug, enhancement

#56 fix: compute threshold with a fixed percentile
  osl_dynamics/analysis/gmm.py
Labels: bug

#57 Feat: new connectivity map functions: eigenvector connectivity, spectral re-ordering.
  osl_dynamics/analysis/connectivity.py
Labels: enhancement

#59 Feat: option to learn diagonal covariances (HMM/DyNeMo)
  osl_dynamics/inference/layers.py
  osl_dynamics/models/dynemo.py
  osl_dynamics/models/dynemo_obs.py
  osl_dynamics/models/hmm.py
Labels: enhancement
