Repository OHBA-analysis/osl-dynamics, pull requests merged in 2023-11, with the labels that each got.

#203 Bugs in thresholding and saving FC networks
  osl_dynamics/analysis/connectivity.py
Labels: bug

#202 Multiple GPU training and prepare for newer TF versions
  osl_dynamics/data/base.py
  osl_dynamics/inference/layers.py
  osl_dynamics/models/__init__.py
  osl_dynamics/models/inf_mod_base.py
  osl_dynamics/models/mod_base.py
Labels: enhancement

#205 Data preparation.
  osl_dynamics/data/base.py
Labels: bug, enhancement
